# Complete Numpy Documentattion 

 # Uses Of Numpy 

- Arithmatic Operation
- Statistical Operation
- Bitwise Operation
- Copying & Viewing Array
- Stacking
- Matrix Operation
- Linear algebra
- Broadcasting
- Mathematical Operations
- Searching Sorting & Counting  

# 1 .Array Creation Function 

In [2]:
import numpy as np

In [3]:
# create an array from a list 
a = np.array([1,2,3,4,5,6,7])
print("Array a :",a )

Array a : [1 2 3 4 5 6 7]


In [4]:
# crate an array with evenly spaced value 
b = np.arange(0,10,3)  # values from 0 to 10 
print("array b :",b)

array b : [0 3 6 9]


In [5]:
# create an array filled with zeros 
d = np.zeros((2,3)) # 2x3 array of zeroes 
print("array d :\n ",d) # /n gives output on new line 

array d :
  [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# crete an array filled with ones 
e = np.ones((2,3))
print('array e :\n',e)

array e :
 [[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# create an identity matrix 
f = np.eye(4)
print("Idntity matrix f : \n",f)

Idntity matrix f : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


 # 2) Array manipulation function 

In [12]:
# Reshape an array 
a1 = np.array ([1,2,3])
reshaped = np.reshape(a1,(1,3))  # Reshaped to 1x3
print("Reshaped array :",reshaped)

Reshaped array : [[1 2 3]]


In [15]:
# flatten an array 
f1 = np.array ([[1,2],[3,4],[5,6],[7,8,],[9,10]])
flattened = np.ravel (f1)  # flatten to 1d Array 
print(" Flatetend array :",flattened)

 Flatetend array : [ 1  2  3  4  5  6  7  8  9 10]


In [19]:
# Transposed an array 
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)  # Transpose the array 
print('Transposed aaray :\n',transposed)

Transposed aaray :
 [[1 3]
 [2 4]]


In [21]:
# stack array verically 
a3 = np.array ([1,2])
a4 = np.array([3,4])
stacked = np.vstack([a3,a4]) # stack a & b Vertically 
print('stacked arrays\n',stacked)

stacked arrays
 [[1 2]
 [3 4]]


In [22]:
# stack array Horizonatal 
a3 = np.array ([1,2])
a4 = np.array([3,4])
stacked = np.hstack([a3,a4]) # stack a and b horizontally 
print('stacked arrays;\n',stacked)

stacked arrays;
 [1 2 3 4]


# 3.Mathematical Functions

In [23]:
# add to arrays 
b = np.array ([1,2,3,4])
added = np.add(b,2)   # add 2 element in each element 
print ('added 2 to b;',added)

added 2 to b; [3 4 5 6]


In [24]:
# square each element 
square = np.power(b,2)  # square each element 
print('squared b :',square)

squared b : [ 1  4  9 16]


In [25]:
# square root of each element 
sqrt_val = np.sqrt(b)
print('square root of b :',sqrt_val)

square root of b : [1.         1.41421356 1.73205081 2.        ]


In [26]:
print (a)

[1 2 3 4 5 6 7]


In [27]:
print(b)

[1 2 3 4]


In [28]:
a3 = np.array([1,2,3])
dot_product= np.dot(a,b)
print ('dot product of the a & b ;',dot_product)

ValueError: shapes (7,) and (4,) not aligned: 7 (dim 0) != 4 (dim 0)

- error happenes beacuse those two arrays has different size of element 

In [29]:
a2 = np.array([1,2,3])
a3 = np.array([4,5,6])
dot_product = np.dot(a2,a3)
print('dot product of a2 & a3:',dot_product)

dot product of a2 & a3: 32


# 4. Statistical function 

In [3]:
import numpy as np 
s = np.array([1,2,3,4])
mean = np.mean(s)
print('mean of s :',mean)   

mean of s : 2.5


In [4]:
# varience  of an array 
var = np.var(s)
print('varience of s :',var)

varience of s : 1.25


In [5]:
#standard deviation on array 
std_dev = np.std(s)
print('stardard deviation of s:',std_dev)

stardard deviation of s: 1.118033988749895


In [6]:
s

array([1, 2, 3, 4])

In [8]:
# minimum element of an array 
minimum = np.min(s)
print('minimum of s :',minimum )

minimum of s : 1


In [9]:
# maximum element of an array 
maximum = np.max(s)
print('maximum of s:',maximum)

maximum of s: 4


# 5. Linear Algebra Function 

In [10]:
# Create a Matrix 
matrix =np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

# 6 . Random Sampling function 

In [12]:
# Generate ramdom values between 0 and 1 
random_vals = np.random.rand(3) # array of 3 random values between 0 & 1
random_vals

array([0.93773043, 0.86647398, 0.80864567])

In [16]:
r1 = np.random.rand(3,4) # create a 3 value in one array & crete the 3 arrays 
r1     

array([[0.87283397, 0.89494053, 0.72674406, 0.50467098],
       [0.58445045, 0.80355428, 0.79128767, 0.55300397],
       [0.10088558, 0.48775662, 0.9524378 , 0.07535608]])

In [ ]:
# set seed for reproducibility
np.random.seed(0)
# 

In [21]:
# Set seed for reproducibility
np.random.seed(1) 

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [25]:
r2 = np.random.rand(2,3,4)

In [26]:
r2

array([[[0.03905478, 0.16983042, 0.8781425 , 0.09834683],
        [0.42110763, 0.95788953, 0.53316528, 0.69187711],
        [0.31551563, 0.68650093, 0.83462567, 0.01828828]],

       [[0.75014431, 0.98886109, 0.74816565, 0.28044399],
        [0.78927933, 0.10322601, 0.44789353, 0.9085955 ],
        [0.29361415, 0.28777534, 0.13002857, 0.01936696]]])

In [28]:
# Generate random integers 
rand_ints = np.random.randint(0, 20, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints) 

Random integers: [10 15 15  7 19]


In [29]:
# Generate random integers 
rand_ints = np.random.randint(0, 10, 5)  # Random integers between 0 and 10
print("Random integers:", rand_ints) 

Random integers: [0 8 7 7 1]


In [47]:
# set seed for reprocibility
np.random.seed(1)
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 8 9 5 0]


# 7. Boolean & logical Function 

In [48]:
# check if all elements are true 
#all
l = np.array([True,False,True,False])
all_true = np.all(l)
print('all elements are :',all_true)


all elements are : False


In [49]:
b = np.array([True,True,True,True])
all_true = np.all(b)
print('all b are true :',all_true)

all b are true : True


In [51]:
c =np.array([False,False,False])
al_t = np.all(c)
print('all c are true :',al_t)

all c are true : False


In [52]:
c =np.array([True,True,False])
al_t = np.all(c)
print('all c are true :',al_t)

all c are true : False


In [53]:
any_true = np.any(c)
print(any_true)

True


In [55]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: True


# 8. Set operations

In [56]:
# Intersaction Of two arrays
set_1 = np.array([1,2,3,4])
set_2 = np.array([3,4,5,6])
intersection = np.intersect1d(set_1,set_2)
print('intersection of a & b:',intersection)

intersection of a & b: [3 4]


In [59]:
# union of two arrays 
union = np.union1d(set_1,set_2)
print('union of a & b :',union )


union of a & b : [1 2 3 4 5 6]


# 9. Array Attribute Function 

In [61]:
# array attributes
a = np.array([1,2,3])
shape = a.shape  # Shape of the array 
size = a.size    # number of elemnt 
dimension = a.ndim  # number of the dimensions 
dtype = a.dtype     # data Type of the array 

print('shape of a :',shape)
print('size of a : ',size)
print('number of dimensions of a:',dimension)
print('data type of the a :',dtype)

shape of a : (3,)
size of a :  3
number of dimensions of a: 1
data type of the a : int64


# 10 . Other Functions 

In [65]:
# created a copy of array 
a = np.array([1,2,3])
cp = np.copy(a)
print('copied array :',cp)

copied array : [1 2 3]


In [67]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes # Size in bytes
print('size of a in bytes :',array_size_in_bytes)

size of a in bytes : 24


In [68]:
# Check if two arrays share memory
shared = np.shares_memory(a, cp)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
